name: docs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.0
    jitsi_meet: ^1.0.0
    permission_handler: ^4.0.0
    get: ^4.6.1
    http: ^0.12.2
    shared_preferences: ^2.0.12
    url_launcher: ^5.7.10
    simple_animations: ^2.3.0
    flutter_sinusoidals: ^0.1.4
    intl: ^0.16.1
    transparent_image: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.8.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/foreground.png"
  image_path_android: "assets/images/foreground.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/foreground.png"

flutter:
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/poppins/Poppins-Regular.ttf
                weight: 100
              - asset: assets/fonts/poppins/Poppins-Medium.ttf
                weight: 200
              - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
                weight: 400
              - asset: assets/fonts/poppins/Poppins-Bold.ttf
                weight: 600
              - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
                weight: 800

    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
